alias ml='sudo tail -f /var/log/mosquitto/mosquitto.log'
alias ol='sudo tail -f /var/log/openhab2/openhab.log'
alias nl='sudo tail -f /var/log/nginx/error.log'
alias nrst='sudo service nginx restart'
alias ntst='sudo nginx -t'
alias or='sudo service openhab2 restart'
alias cs='/usr/local/projects/tools/checkservice.sh'
alias items='sudo vim /usr/local/projects/openhab2/items/qq010.items'
alias itemsa='sudo vim /usr/local/projects/openhab2/items/admin.items'
alias sitemap='sudo vim /usr/local/projects/openhab2/sitemaps/qq010.sitemap'
alias sitemapa='sudo vim /usr/local/projects/openhab2/sitemaps/admin.sitemap'
alias persistence='sudo vim /usr/local/projects/openhab2/persistence/mysql.persist'
alias rules='sudo vim /usr/local/projects/openhab2/rules/qq010.rules'
alias gitpull='/home/ubuntu/reload_conf.sh'

